# Generated by Django 3.1.7 on 2022-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20220814_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importancy',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
